Repository litmuschaos/litmus-docs, pull requests merged in 2021-03, with the labels that each got.

#9 [doc] Introduction page addition.
  website/docs/assets/litmus-overview.png
  website/docs/introduction.md
Labels: documentation

#10 ̶U̶p̶d̶a̶t̶e̶d̶ ̶D̶i̶r̶e̶c̶t̶o̶r̶y̶ ̶S̶t̶r̶u̶c̶t̶u̶r̶e̶ + Initial Sidebar Setup
  website/docs/agent-installation.md
  website/docs/create.md
  website/docs/diagram.md
  website/docs/litmus-installation.md
  website/docs/observe.md
  website/docs/old-vs-new.md
  website/docs/schedule.md
  website/docs/uninstall.md
  website/docusaurus.config.js
  website/sidebars.js
Labels: enhancement, good first issue

#11 Added github-action workflow for Spelling Checks in Docs.
  .github/workflows/Pull_Request.yml
  .spellcheck.yml
  .wordlist.txt
  website/docs/old-vs-new.md
Labels: documentation, enhancement

#14 Architecture Doc Section
  website/docs/architecture.md
  website/docs/assets/portal-arch.jpg
  website/docs/assets/red-blue-cluster.png
  website/docs/diagram.md
  website/docs/introduction.md
  website/docusaurus.config.js
  website/sidebars.js
Labels: documentation

#12 chore(docs): Added Docs for Probes
  .wordlist.txt
  website/docs/probes.md
  website/sidebars.js
Labels: documentation

#13 chore(docs): Added docs for MyHub
  website/docs/myhub.md
  website/sidebars.js
Labels: documentation

#19 chore(docs): Added Litmus Installation Docs
  .wordlist.txt
  website/docs/litmus-installation.md
  website/sidebars.js
Labels: documentation

#18 chore(docs): Added docs for observe and update workflows
  website/docs/assets/experiment-graph.png
  website/docs/observe.md
  website/docs/update.md
  website/sidebars.js
Labels: documentation

#23 Added Minor Installation Changes.
  website/docs/litmus-installation.md
  website/versioned_docs/version-2.0.0-Beta-1/litmus-installation.md
Labels: documentation
